# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_confirm',
        ),
    ]
