# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_remove_user_password_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
