# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='loginname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='loginpass',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password_confirm',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=3, max_length=45),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
